CourierCastingApp/ViewComponents/NavigationBarViewComponent.cs
using CourierCastingApp.Helpers;
using CourierCastingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace CourierCastingApp.ViewComponents
{
    public class NavigationBarViewComponent:ViewComponent
    {
        Dictionary<ClientStatus, List<NavBarViewModel>> dictionaryNavBar = new Dictionary<ClientStatus, List<NavBarViewModel>>();

        public NavigationBarViewComponent()
        {
            // Initialize the dictionary with default values
            dictionaryNavBar = new Dictionary<ClientStatus, List<NavBarViewModel>>
        {
            { ClientStatus.Client, new List<NavBarViewModel>
                {
                    new NavBarViewModel { Text = "Start", Url = "/", ControllerName = "Home"},
                    new NavBarViewModel { Text = "Dostarcz Paczkę", Url = "/DeliverParcel", ControllerName = "DeliverParcel" },
                    new NavBarViewModel { Text = "Historia Zamówień", Url = "/OrderHistory", ControllerName = "OrderHistory" },
                }
            },
            { ClientStatus.Courier, new List<NavBarViewModel>
                {
                    new NavBarViewModel { Text = "Start", Url = "/", ControllerName = "Home"},
                    new NavBarViewModel { Text = "Zamówienia", Url = "/Deliveries", ControllerName = "Deliveries" }
                }
            },
            { ClientStatus.OfficeWorker, new List<NavBarViewModel>
                {
                    new NavBarViewModel { Text = "Start", Url = "/", ControllerName = "Home"},
                    new NavBarViewModel { Text = "Wyszukania", Url = "/Inquiries", ControllerName = "Inquiries" },
                    new NavBarViewModel { Text = "Zamówienia", Url = "/OfferRequests", ControllerName = "OfferRequests" },
                }
            },
        };
        }

        public IViewComponentResult Invoke()
        {
            // We must provide there some kind of getting from database of status or just getting from model 
            ClientStatus userRole = ClientStatus.Client;

            return View(dictionaryNavBar[userRole]);
        }
    }
}

CourierCastingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourierCastingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourierCastingApp.styles.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/css/bootstrap-timepicker.min.css">
    @RenderSection("Stylesheets", required: false)
</head>
<body>
    <header>
        @await Component.InvokeAsync("NavigationBar")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CourierCastingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/js/bootstrap-timepicker.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>