CourierCastingApp/Controllers/Client/DeliverParcelController.cs
using CourierCastingApp.DataTransferObjects;
using CourierCastingApp.Models;
using CourierCastingApp.Models.Forms;
using CourierCastingApp.Services;
using CourierCastingApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace CourierCastingApp.Controllers.Client
{
	public class DeliverParcelController : Controller
	{
		private IInquiryRepository _inquiryRepository;
		private ICourierRepository _courierRepository;

		public DeliverParcelController(IInquiryRepository inquiryRepository, ICourierRepository courierRepository)
		{
			_inquiryRepository = inquiryRepository;
			_courierRepository = courierRepository;
        }

		public IActionResult Index()
		{
			//TempData.Remove("MemoryInquiryResult");
				// If model is null, create a new instance
			if (TempData["MemoryInquiryResult"] is not null)
			{
				var viewModel = JsonConvert.DeserializeObject<InquiryResultVm>(TempData["MemoryInquiryResult"].ToString());
				return View(viewModel);
			}

			return View(new InquiryResultVm());
		}

		[HttpPost]
		public async Task<IActionResult> AddInquiryForm(InquiryResultVm model, int courierId)
		{
			if (model.validateInquiryModel())
			{
				var courier = new CourierDto(model.BestCouriers[courierId]);
                InquiryDto inquiryDto = new InquiryDto(model.InquiryModel, courier);

				var result = await _inquiryRepository.CreateInquiry(inquiryDto);

				if (result.isFailure)
					return StatusCode(500);

                if (result.Success)
				{
					TempData["SuccessMessage"] = "Inquiry created successfully!";
					return RedirectToAction("Index");
				}
			}

            return View("Index");
        }

		[HttpPost]
		public async Task<IActionResult> GetBestCourier(InquiryResultVm model)
		{
			InquiryResultVm viewModel = new InquiryResultVm
			{
				InquiryModel = model.InquiryModel
			};

			// Explicitly validate InquiryModel
			if (model.validateInquiryModel())
			{
				bool isWeekend = checkIfWeekend(model.InquiryModel.DeliveryDate);
				model.InquiryModel.WeekendDelivery = isWeekend;

                InquiryDto inquiryDto = new InquiryDto(model.InquiryModel);

				var result = await _courierRepository.GetBestCouriers(inquiryDto);
				viewModel.Success = result.Success;

				if (result.Success)
				{
					viewModel.Message = "Courier successfully obtained!";
					var couriers = new List<CourierVm>();

					foreach (var item in result.Value)
					{
						var courier = new CourierVm(item);
						couriers.Add(courier);
					}
					viewModel.BestCouriers = couriers.ToArray();
				} else
				{
					viewModel.Message = "No couriers";
				}

                TempData["MemoryInquiryResult"] = JsonConvert.SerializeObject(viewModel);
                return RedirectToAction("Index");
            }
			return View("Index");
        }
        public bool checkIfWeekend(DateOnly date)
        {
            int day = (int)date.DayOfWeek;
            return day == 6 || day == 0;
        }
    }
}

CourierCastingApp/Views/DeliverParcel/Index.cshtml
@model CourierCastingApp.ViewModels.InquiryResultVm
@{
	ViewData["Title"] = "Delivery Parcel";
}

@section Stylesheets {
    <link rel="stylesheet" href="~/css/deliverForm.css" />
}

<div><h1>deliver parcel</h1></div>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@await Html.PartialAsync("_PartialDeliverForm")

@section Scripts {
	<script src="~/js/deliverForm.js"></script>
}

CourierCastingApp/Views/DeliverParcel/_PartialDeliverForm.cshtml
@model CourierCastingApp.ViewModels.InquiryResultVm;

@if (Model != null && Model.Success)
{
    @for (int i = 0; i < Model.BestCouriers.Length; i++)
    {
        var courier = Model.BestCouriers[i];

        <div class="courier-form">
            <p>Drivers route: @courier.Start-@courier.End</p>
            @if (Model.InquiryModel.HighPriority)
            {
                <p>Cost: @courier.CenaHighPriority</p>
            }
            else
            {
                <p>Cost: @courier.Cena</p>
            }

            @using (Html.BeginForm("AddInquiryForm", "DeliverParcel", FormMethod.Post))
            {
                @Html.HiddenFor(model => model.InquiryModel)
                @Html.HiddenFor(model => model.InquiryModel.StartLocation.Street)
                @Html.HiddenFor(model => model.InquiryModel.StartLocation.StreetNumber)
                @Html.HiddenFor(model => model.InquiryModel.StartLocation.City)
                @Html.HiddenFor(model => model.InquiryModel.StartLocation.PostCode)
                @Html.HiddenFor(model => model.InquiryModel.StartLocation.Country)
                @Html.HiddenFor(model => model.InquiryModel.EndLocation.Street)
                @Html.HiddenFor(model => model.InquiryModel.EndLocation.StreetNumber)
                @Html.HiddenFor(model => model.InquiryModel.EndLocation.City)
                @Html.HiddenFor(model => model.InquiryModel.EndLocation.PostCode)
                @Html.HiddenFor(model => model.InquiryModel.EndLocation.Country)
                @Html.HiddenFor(model => model.InquiryModel.Name)
                @Html.HiddenFor(model => model.BestCouriers[i].Id)
                @Html.HiddenFor(model => model.BestCouriers[i].Start)
                @Html.HiddenFor(model => model.BestCouriers[i].End)
                @Html.HiddenFor(model => model.BestCouriers[i].Cena)
                @Html.HiddenFor(model => model.BestCouriers[i].CenaHighPriority)
                @Html.HiddenFor(model => model.BestCouriers[i].CzyWeekend)
                @Html.HiddenFor(model => model.BestCouriers[i].Workload)
                @Html.HiddenFor(model => model.BestCouriers[i].MaxPackages)
                @Html.HiddenFor(courierId => i)
                <input type="submit" class="btn btn-primary" value="Select Courier" />
            }
        </div>
    }
}

@if (Model != null && Model.Message == "No couriers")
{
    <div class="alert alert-danger">
        <h3>Couldn't find courier with this route</h3>
    </div>
}

@using (Html.BeginForm("GetBestCourier", "DeliverParcel", FormMethod.Post, new { id = "InquiryForm" }))
{
    <div class="form-group">
        <label asp-for="InquiryModel.DimX">Dimension X (cm)</label>
        <input asp-for="InquiryModel.DimX" class="form-control" />
        <span asp-validation-for="InquiryModel.DimX" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InquiryModel.DimY">Dimension Y (cm)</label>
        <input asp-for="InquiryModel.DimY" class="form-control" />
        <span asp-validation-for="InquiryModel.DimY" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InquiryModel.DimZ">Dimension Z (cm)</label>
        <input asp-for="InquiryModel.DimZ" class="form-control" />
        <span asp-validation-for="InquiryModel.DimZ" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InquiryModel.Weight">Weight (gram)</label>
        <input asp-for="InquiryModel.Weight" class="form-control" />
        <span asp-validation-for="InquiryModel.Weight" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InquiryModel.DeliveryDate">Delivery Date</label>
        <div class="input-group date" data-provide="datepicker">
            <input asp-for="InquiryModel.DeliveryDate" class="form-control" />
            <div class="input-group-addon">
                <span class="glyphicon glyphicon-th"></span>
            </div>
        </div>
        <span asp-validation-for="InquiryModel.DeliveryDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InquiryModel.DeliveryTime">Delivery Time</label>
        <div class="input-group timepicker">
            <input asp-for="InquiryModel.DeliveryTime" class="form-control" />
            <div class="input-group-append">
                <span class="input-group-text">
                    <i class="fa fa-clock-o"></i>
                </span>
            </div>
        </div>
        <span asp-validation-for="InquiryModel.DeliveryTime" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InquiryModel.Name">Name</label>
        <input asp-for="InquiryModel.Name" class="form-control" />
        <span asp-validation-for="InquiryModel.Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="InquiryModel.HighPriority">High Priority</label>
        <div class="custom-control custom-checkbox">
            <input asp-for="InquiryModel.HighPriority" class="custom-control-input" type="checkbox" id="chkHighPriority">
            <label class="custom-control-label" for="chkHighPriority">Yes</label>
        </div>
        <span asp-validation-for="InquiryModel.HighPriority" class="text-danger"></span>
    </div>

    <!-- Repeat the above structure for other properties of InquiryFormModel -->

    <div class="form-group">
        <h4>Start Location</h4>
        <label asp-for="InquiryModel.StartLocation.Street">Street</label>
        <input asp-for="InquiryModel.StartLocation.Street" class="form-control" />
        <span asp-validation-for="InquiryModel.StartLocation.Street" class="text-danger"></span>

        <label asp-for="InquiryModel.StartLocation.StreetNumber">StreetNumber</label>
        <input asp-for="InquiryModel.StartLocation.StreetNumber" class="form-control" />
        <span asp-validation-for="InquiryModel.StartLocation.StreetNumber" class="text-danger"></span>

        <label asp-for="InquiryModel.StartLocation.City">City</label>
        <input asp-for="InquiryModel.StartLocation.City" class="form-control" />
        <span asp-validation-for="InquiryModel.StartLocation.City" class="text-danger"></span>

        <label asp-for="InquiryModel.StartLocation.PostCode">PostCode</label>
        <input asp-for="InquiryModel.StartLocation.PostCode" class="form-control" />
        <span asp-validation-for="InquiryModel.StartLocation.PostCode" class="text-danger"></span>

        <label asp-for="InquiryModel.StartLocation.Country">Country</label>
        <input asp-for="InquiryModel.StartLocation.Country" class="form-control" />
        <span asp-validation-for="InquiryModel.StartLocation.Country" class="text-danger"></span>



        <h4>End Location</h4>
        <label asp-for="InquiryModel.EndLocation.Street">Street</label>
        <input asp-for="InquiryModel.EndLocation.Street" class="form-control" />
        <span asp-validation-for="InquiryModel.EndLocation.Street" class="text-danger"></span>

        <label asp-for="InquiryModel.EndLocation.StreetNumber">StreetNumber</label>
        <input asp-for="InquiryModel.EndLocation.StreetNumber" class="form-control" />
        <span asp-validation-for="InquiryModel.EndLocation.StreetNumber" class="text-danger"></span>

        <label asp-for="InquiryModel.EndLocation.City">City</label>
        <input asp-for="InquiryModel.EndLocation.City" class="form-control" />
        <span asp-validation-for="InquiryModel.EndLocation.City" class="text-danger"></span>

        <label asp-for="InquiryModel.EndLocation.PostCode">PostCode</label>
        <input asp-for="InquiryModel.EndLocation.PostCode" class="form-control" />
        <span asp-validation-for="InquiryModel.EndLocation.PostCode" class="text-danger"></span>

        <label asp-for="InquiryModel.EndLocation.Country">Country</label>
        <input asp-for="InquiryModel.EndLocation.Country" class="form-control" />
        <span asp-validation-for="InquiryModel.EndLocation.Country" class="text-danger"></span>

    </div>

    <button type="submit" class="btn btn-primary">Search Courier</button>
}